name: Build and Release Win64

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package .love file
        uses: love-actions/love-actions-core@v1
        with:
          build-list: >-
            ./assets/
            ./data/
            ./lib/
            ./states/
            ./systems/
            ./ui/
            ./conf.lua
            ./main.lua

      - name: Upload .love artifact
        uses: actions/upload-artifact@v4
        with:
          name: core_love_package
          path: ./game.love

  build-windows:
    runs-on: windows-latest
    needs: build-core
    env:
      OUTPUT_FOLDER: ./build
    steps:
      - uses: actions/checkout@v4

      - name: Download .love artifact
        uses: actions/download-artifact@v4
        with:
          name: core_love_package

      - name: Build Windows packages
        id: build-packages
        uses: love-actions/love-actions-windows@v2
        with:
          love-package: ./game.love
          product-name: sector07
          output-folder: ${{ env.OUTPUT_FOLDER }}

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
          name: ${{ github.ref_type == 'tag' && github.ref_name || 'Latest Automated Build' }}
          files: |
            ${{ env.OUTPUT_FOLDER }}/sector07_x64.zip
            ${{ env.OUTPUT_FOLDER }}/sector07_x86.zip
          generate_release_notes: true
          prerelease: ${{ github.ref_type != 'tag' }}
